### ISSUE TITLE
Create Github ditiow.io for the repository

### ISSUE THREAD

**Issue by 0xh3xa** [marcosvidolin/ditiow#22] opened 2020-03-27 12:23 UTC
Create Github ditiow.io  and add the link to be the website in the repository.
Choose a good theme for the page.

**Comment by marcosvidolin** [comment] 2020-03-30 16:28
That's great,
I'll work on it and link this with #18 
 :+1:

**Comment by marcosvidolin** [comment] 2020-03-30 16:33
Duplicate of #18

**Closed as completed** 2020-03-30 17:38 UTC
Labels: documentation
